### ISSUE TITLE
Add P-256 example

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/tls13-vectors#1]
Kazu Yamamoto requests:

> I would be nice if this example includes secp256r1 instead of (or in
  addition to) x25519 as I guess that many TLS 1.3 implementations
  implement secp256r1 first.

**Comment by kazu-yamamoto** [comment]
Thank you for registering this issue.

I'm now trying to add X25519 to my Haskell implementation. But P-256 would much help me.

**Comment by martinthomson** [comment]
Unfortunately, I think that I have to modify NSS to get this test.  Embarassing as it is, we used to test with P-256 all the time, but we switched to X25519 and ended up in a state where I don't have an easy P-256 test case to point you at.  If you can handle P-384, and this is especially urgent, you can modify the draft and run NSS yourself.  You will need to use `SignatureSchemeEcdsaP384/TlsSignatureSchemeConfiguration.P384Priority/0`.

**Comment by kazu-yamamoto** [comment]
Today, my Haskell server implementation finally communicates with Firefox Nightly in TLS 1.3 ID18 both with P256 and X25519.
I will consider how to use your test vectors of X25519 in test suites.

**Comment by martinthomson** [comment]
That's great!  I see that you also added your implementation to the [implementation wiki](https://github.com/tlswg/tls13-spec/wiki/Implementations).  Thanks for doing that.

**Comment by kazu-yamamoto** [comment]
Are there any MLs or channels to discuss implementations?
I noticed that HTTP/1.1 (instead of HTTP/2) is used in TLS 1.3 between Nightly and the Haskell implementation.
So, I added an ALPN extension to Server Hello.
But Nightly rejected this extension.
I would like to know a right place to ask such questions.

**Comment by kazu-yamamoto** [comment]
This is my fault. ALPN should be carried in EE. But I sent it in ServerHello.
Now my TLS 1.3 server in Haskell can communicate with Firefox Nightly and Chrome Canary by HTTP/2 over TLS 1.3.
Anyway, I would like to now a right place to ask questions.

**Comment by martinthomson** [comment]
Send me an email privately and I will send you coordinates.
