### ISSUE TITLE
empty salt

### ISSUE THREAD

**Issue by kazu-yamamoto** [martinthomson/tls13-vectors#2]
salt (0 octets): (empty)

is found twice in the current draft.
But I believe this should be:

    salt (32 octets): 0000000000000000 0000000000000000 0000000000000000 0000000000000000

The figure in Section 7.1. in the TLS 1.3 spec specifies the salt as 0. I admit that there is no clear definition of 0 for salt but I think that 0 means zero values of hash length.

Note that both 0 and "" for salt result in the same output value.

**Comment by martinthomson** [comment]
Yeah, I wasn't sure how to deal with this.  Maybe you can ask for clarification in the TLS spec.  As you say, it doesn't matter if salt is empty, one zero, or any number of zeroes up to the hash input size, but we should maybe clarify that.

**Comment by martinthomson** [comment]
BTW, I chose to log the salt this way because the script that generates the text doesn't know the block size of the hash function.

**Comment by kazu-yamamoto** [comment]
As discussed in https://github.com/tlswg/tls13-spec/issues/784, the salt should be 0s of Hash.length.
So, please fix it.

**Comment by martinthomson** [comment]
Fixed in 1d7e1d5

**Comment by kazu-yamamoto** [comment]
Thank you!
